#!/usr/bin/env bash

echo ""
echo "-------------------------------------------"
echo "            ASUS NVIDIA SETUP"
echo "-------------------------------------------"
echo ""
echo "Reboot recommended for changes to take effect."
echo ""
echo "After reboot, check NVIDIA GPU power management and S0ix support:"
echo ""
echo "1. Ensure NVIDIA DRM modeset is active (early module loading):"
echo "   You should have 'nvidia-drm.modeset=1' in your GRUB kernel parameters"
echo "   GRUB_CMDLINE_LINUX_DEFAULT=\"quiet splash nvidia-drm.modeset=1\""
echo "   and 'options nvidia_drm modeset=1' in /etc/modprobe.d/nvidia.conf."
echo ""
echo "2. Find your GPU bus address (use tab completion):"
echo "   ls /proc/driver/nvidia/gpus/"
echo ""
echo "3. Check power status:"
echo "   cat /proc/driver/nvidia/gpus/<bus_address>/power"
echo ""
echo "You should see something like:"
echo "S0ix Power Management:"
echo " Platform Support:          Supported"
echo " Status:                    Enabled"
echo ""
echo "4. Optional: check GPU state with nvidia-smi"
echo "   nvidia-smi"
echo ""
echo "5. If Status shows 'Disabled':"
echo "   - Confirm nvidia-powerd service is running:"
echo "       systemctl status nvidia-powerd"
echo "   - Confirm NVIDIA modules are loaded:"
echo "       lsmod | grep nvidia"
echo "-------------------------------------------"
