#!/usr/bin/env bash

echo ""
echo "-------------------------------------------"
echo "            ASUS NVIDIA SETUP"
echo "-------------------------------------------"
echo ""
echo "Reboot recommended for changes to take effect."
echo ""
echo "After reboot, check NVIDIA GPU power management and S0ix support:"
echo ""
echo "1. Find your GPU bus address (use tab completion):"
echo "   ls /proc/driver/nvidia/gpus/"
echo ""
echo "2. Check power status:"
echo "   cat /proc/driver/nvidia/gpus/<bus_address>/power"
echo ""
echo "You should see something like:"
echo "S0ix Power Management:"
echo " Platform Support:          Supported"
echo " Status:                    Enabled"
echo ""
echo "3. Optional: check GPU state with nvidia-smi"
echo "   nvidia-smi"
echo "-------------------------------------------"
