#!/usr/bin/env bash

echo ""
echo "-------------------------------------------"
echo "          GRUB THEME MANUAL SETUP"
echo "-------------------------------------------"
echo ""
echo "Edit this file: /etc/default/grub"
echo ""
echo "Add or update:"
echo "   GRUB_THEME=\"/boot/grub/themes/catppuccin-mocha-grub-theme/theme.txt\""
echo ""
echo "Comment:"
echo "   # GRUB_TERMINAL_OUTPUT=console"
echo ""
echo "Then apply changes:"
echo "   sudo grub-mkconfig -o /boot/grub/grub.cfg"
echo ""
echo "-------------------------------------------"
